#!/bin/bash
#
# Description	: Android Build Script.
# Authors		: jianjun jiang - jerryjianjun@gmail.com
# Version		: 2.00
# Notes			: None
#

#
# JAVA PATH
#
export PATH=/usr/lib/jvm/java-7-oracle/bin:$PATH

#
# Some Directories
#
BS_DIR_TOP=$(cd `dirname $0` ; pwd)
BS_DIR_RELEASE=${BS_DIR_TOP}/out/release
BS_DIR_TARGET=${BS_DIR_TOP}/out/target/product/GEC6818/
BS_DIR_KERNEL=${BS_DIR_TOP}/kernel


#
# Cross Toolchain Path
#

BS_CROSS_TOOLCHAIN_KERNEL=${BS_DIR_TOP}/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-

#
# Target Config
#
BS_CONFIG_KERNEL=GEC6818_defconfig
BS_CONFIT_BUILDROOT=GEC6818_defconfig

setup_environment()
{
	LANG=C
	cd ${BS_DIR_TOP};
	mkdir -p out/host/linux-x86/bin || return 1;
	mkdir -p ${BS_DIR_TARGET}/boot;

	[ -f "${BS_DIR_TOP}/out/host/linux-x86/bin/mkuserimg.sh" ] ||{ echo "tar generate boot.img tools"; tar xvf tools/generate_boot.tar.gz -C ${BS_DIR_TOP}/out/host/linux-x86/bin;}
	[ -f "${BS_DIR_TARGET}/boot/root.img.gz" ] ||{ echo "tar boot.tar.gz"; tar xvf tools/boot.tar.gz -C ${BS_DIR_TARGET};}

	PATH=${BS_DIR_TOP}/out/host/linux-x86/bin:$PATH;

	mkdir -p ${BS_DIR_RELEASE} || return 1
}

build_kernel()
{
	export PATH=${BS_DIR_TOP}/tools:$PATH 
	# Compiler kernel
	cd ${BS_DIR_KERNEL} || return 1
	make ${BS_CONFIG_KERNEL} ARCH=arm CROSS_COMPILE=${BS_CROSS_TOOLCHAIN_KERNEL} || return 1
	make -j${threads} ARCH=arm CROSS_COMPILE=${BS_CROSS_TOOLCHAIN_KERNEL} || return 1
	make -j${threads} ARCH=arm CROSS_COMPILE=${BS_CROSS_TOOLCHAIN_KERNEL} uImage || return 1

	# Copy uImage to release directory
	cp -v ${BS_DIR_KERNEL}/arch/arm/boot/uImage ${BS_DIR_RELEASE}


	# generate boot.img
	cd ${BS_DIR_TOP} || return 1
	echo 'boot.img ->' ${BS_DIR_RELEASE}
	# Make boot.img with ext4 format, 64MB
	cp -v ${BS_DIR_KERNEL}/arch/arm/boot/uImage ${BS_DIR_TARGET}/boot
	mkuserimg.sh -s ${BS_DIR_TARGET}/boot ${BS_DIR_TARGET}/boot.img ext4 boot 67108864

	cp -av ${BS_DIR_TARGET}/boot.img ${BS_DIR_RELEASE} || return 1;
	return 0
}

threads=4
kernel=no


if [ -z $1 ]; then
	kernel=yes
fi

while [ "$1" ]; do
    case "$1" in
	-j=*)
		x=$1
		threads=${x#-j=}
		;;
	
	-k|--kernel)
	    kernel=yes
		;;
    esac
    shift
done

setup_environment || exit 1

if [ "${kernel}" = yes ]; then
	build_kernel || exit 1
fi


exit 0
