#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-hisiv510-linux-gcc -O"
  #define PLATFORM "dist"
  #define DATE "Mon May 10 00:53:10 CST 2021"
#endif
